local lib = loadstring(game:HttpGet("https://raw.githubusercontent.com/TNightmareHA/Backup/main/Discord"))()
local win = lib:Window("Example")
local serv = win:Server("Test", "V0.1")
local btns = serv:Channel("Example Buttons")
btns:Button("Kill all - Test", function()
        DiscordLib:Notification("Notification", "Killed everyone!", "Okay!")
end)
btns:Seperator()
btns:Button("Get max level", function()
    DiscordLib:Notification("Notification", "Example - Max level!", "Test - Okay!")
end)
local tgls = serv:Channel("Example Toggles")
tgls:Toggle("Auto-Farm",false, function(bool)
        print("Now: "..bool)
end)
local sldrs = serv:Channel("Example - Sliders")
local sldr = sldrs:Slider("Test - Slide me!", 0, 1000, 400, function(t)
        print(t)
end)
sldrs:Button("Change to 50", function()
        sldr:Change(50)
end)
local drops = serv:Channel("Example Dropdowns")
local drop = drops:Dropdown("Pick me!", {"Option 1","Option 2","Option 3","Option 4","Option 5"}, function(bool)
        print(bool)
end)
drops:Button("Example Clear", function()
        drop:Clear()
end)
drops:Button("Test - Add option", function()
        drop:Add("Option")
end)
local clrs = serv:Channel("Test - Colorpickers")
clrs:Colorpicker("ESP Color", Color3.fromRGB(255,1,1), function(t)
        print(t)
end)
local textbs = serv:Channel("Example Textboxes")
textbs:Textbox("Test - Gun power", "Test - Type here!", true, function(t)
        print(t)
end)
local lbls = serv:Channel("Example Labels")
lbls:Label("Test - This is just a label.")
local bnds = serv:Channel("Binds")
bnds:Bind("Test - Kill bind", Enum.KeyCode.RightShift, function()
        print("Killed everyone!")
end)
serv:Channel("by TheNightmareHorrorAttraction#3004")
win:Server("Example Main", "http://www.roblox.com/asset/?id=6031075938")
